'use client';

import { useEffect, useMemo, useState } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { ArrowRight, BedDouble, Check, ChevronDown, Globe2, Heart, Hotel, MapPin, Menu, MessageCircle, Plane, Search, SlidersHorizontal, Sparkles, Ticket, X, Phone, CalendarDays, Users, Scale, Share2 } from 'lucide-react';

const WA = '213672783789';
const PHONE = 'tel:+213672783789';
const GENERAL = 'tel:+213770423090';

const trips = [
  {id:'istanbul', title:'Istanbul', country:'Turquie', type:'Voyage international', duration:'Sur demande', departure:'Khemis Miliana', style:'Culture · City break', image:'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=85'},
  {id:'dubai', title:'Dubai', country:'Émirats arabes unis', type:'Voyage international', duration:'Sur demande', departure:'Khemis Miliana', style:'Luxe · Shopping', image:'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=85'},
  {id:'tunis', title:'Tunis', country:'Tunisie', type:'Voyage international', duration:'Sur demande', departure:'Khemis Miliana', style:'Plage · Culture', image:'https://images.unsplash.com/photo-1530406831759-347e4f3e5e9f?auto=format&fit=crop&w=1200&q=85'},
  {id:'mecca', title:'Omra', country:'Arabie Saoudite', type:'Omra', duration:'Programme sur demande', departure:'Khemis Miliana', style:'Religieux', image:'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&w=1200&q=85'},
  {id:'paris', title:'Paris', country:'France', type:'Voyage international', duration:'Sur demande', departure:'Khemis Miliana', style:'Culture · City break', image:'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=85'},
  {id:'algeria', title:'Algérie', country:'Algérie', type:'Voyage local', duration:'Sur demande', departure:'Khemis Miliana', style:'Aventure · Culture', image:'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=85'}
];

const nav = [['Accueil','/'],['Voyages','/voyages'],['Destinations','/destinations'],['Omra','/omra'],['Billetterie','/billetterie'],['Hôtels','/hotels'],['Offres','/offres'],['Agences','/agences'],['À propos','/a-propos'],['Contact','/contact']];

function whatsapp(text:string){ return `https://wa.me/${WA}?text=${encodeURIComponent(text)}`; }

export default function Page(){
  const pathname = usePathname();
  const router = useRouter();
  const [menu,setMenu]=useState(false);
  const [query,setQuery]=useState('');
  const [favorites,setFavorites]=useState<string[]>([]);
  const [compare,setCompare]=useState<string[]>([]);
  const [toast,setToast]=useState('');

  useEffect(()=>{ try { setFavorites(JSON.parse(localStorage.getItem('pt-favorites')||'[]')); setCompare(JSON.parse(localStorage.getItem('pt-compare')||'[]')); } catch {} },[]);
  const toggleFavorite=(id:string)=>{ const next=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id]; setFavorites(next); localStorage.setItem('pt-favorites',JSON.stringify(next)); };
  const toggleCompare=(id:string)=>{ if(!compare.includes(id)&&compare.length>=3){setToast('Vous pouvez comparer jusqu’à 3 voyages.');return;} const next=compare.includes(id)?compare.filter(x=>x!==id):[...compare,id]; setCompare(next); localStorage.setItem('pt-compare',JSON.stringify(next)); };
  const doSearch=()=>{ router.push(`/voyages?destination=${encodeURIComponent(query)}`); };

  const page = pathname === '/' ? 'home' : pathname.split('/').filter(Boolean)[0] || 'home';
  const slug = pathname.split('/').filter(Boolean).slice(1).join('/');

  return <div className="site-shell">
    <header className="header"><div className="container nav-wrap">
      <button className="brand" onClick={()=>router.push('/')} aria-label="PRIMATOURS accueil"><span className="brand-orbit"><Globe2 size={25}/></span><span><b>PRIMA</b><strong>TOURS</strong><small>AGENCE DE VOYAGE</small></span></button>
      <nav className="desktop-nav">{nav.map(([label,href])=><button key={href} className={pathname===href?'active':''} onClick={()=>router.push(href)}>{label}</button>)}</nav>
      <div className="nav-actions"><button className="lang">FR <span>/</span> AR</button><button className="btn btn-red" onClick={()=>router.push('/demande')}>Demander un devis</button><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Menu"><Menu/></button></div>
    </div>{menu&&<div className="mobile-menu">{nav.map(([label,href])=><button key={href} onClick={()=>{setMenu(false);router.push(href)}}>{label}</button>)}<button className="btn btn-red" onClick={()=>{setMenu(false);router.push('/demande')}}>Demander un devis</button></div>}</header>

    {page==='home' && <Home query={query} setQuery={setQuery} doSearch={doSearch} router={router} favorites={favorites} toggleFavorite={toggleFavorite} compare={compare} toggleCompare={toggleCompare}/>} 
    {page==='voyages' && <Listing title="Voyages" subtitle="Trouvez une expérience qui correspond à votre prochaine aventure." query={query} setQuery={setQuery} doSearch={doSearch} favorites={favorites} toggleFavorite={toggleFavorite} compare={compare} toggleCompare={toggleCompare}/>} 
    {page==='destinations' && (slug ? <Destination slug={slug} router={router}/> : <Listing title="Destinations" subtitle="Des idées de départ pour construire votre prochain voyage." query={query} setQuery={setQuery} doSearch={doSearch} favorites={favorites} toggleFavorite={toggleFavorite} compare={compare} toggleCompare={toggleCompare}/>) }
    {page==='offres' && <Listing title="Offres & programmes" subtitle="Découvrez les programmes disponibles sur demande auprès de Primatours." query={query} setQuery={setQuery} doSearch={doSearch} favorites={favorites} toggleFavorite={toggleFavorite} compare={compare} toggleCompare={toggleCompare}/>} 
    {page==='omra' && <ServicePage kind="omra" router={router}/>} 
    {page==='billetterie' && <ServicePage kind="ticket" router={router}/>} 
    {page==='hotels' && <ServicePage kind="hotel" router={router}/>} 
    {page==='agences' && <Branches router={router}/>} 
    {page==='a-propos' && <About router={router}/>} 
    {page==='contact' && <Contact/>} 
    {page==='demande' && <RequestPage/>} 
    {page==='favorites' && <Favorites favorites={favorites} toggleFavorite={toggleFavorite} router={router}/>} 
    {page==='compare' && <Compare compare={compare} toggleCompare={toggleCompare} router={router}/>} 

    <Footer router={router}/>
    <div className="mobile-cta"><a href={PHONE}><Phone size={17}/> Appeler</a><a href={whatsapp('Bonjour Primatours Khemis Miliana, je souhaite obtenir des informations.')}><MessageCircle size={17}/> WhatsApp</a><button onClick={()=>router.push('/demande')}><Sparkles size={17}/> Demander</button></div>
    {toast&&<button className="toast" onClick={()=>setToast('')}>{toast} <X size={16}/></button>}
  </div>
}

function Home({query,setQuery,doSearch,router,favorites,toggleFavorite,compare,toggleCompare}:{query:string,setQuery:(x:string)=>void,doSearch:()=>void,router:any,favorites:string[],toggleFavorite:(x:string)=>void,compare:string[],toggleCompare:(x:string)=>void}){
 return <main>
  <section className="hero"><div className="hero-overlay"/><div className="container hero-content"><div className="eyebrow"><span/> PRIMATOURS · KHÉMIS MILIANA</div><h1>Votre voyage<br/><em>commence ici.</em></h1><p>Voyages organisés, Omra, billetterie et réservation d’hôtels avec Primatours.</p><div className="hero-buttons"><button className="btn btn-red btn-lg" onClick={()=>router.push('/voyages')}>Explorer les voyages <ArrowRight size={18}/></button><button className="btn btn-glass btn-lg" onClick={()=>router.push('/demande')}>Demander un devis</button></div></div>
   <div className="search-panel container"><div className="search-head"><div><span className="kicker">RECHERCHE INTELLIGENTE</span><h2>Où souhaitez-vous partir ?</h2></div><span className="search-note">Ex. « Je cherche un voyage à Istanbul pour 2 personnes. »</span></div><div className="search-grid"><label className="search-input"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&doSearch()} placeholder="Destination ou demande libre..."/></label><label><span>Type de voyage</span><select><option>Tous les types</option><option>Voyage organisé</option><option>Omra</option><option>Hôtel</option><option>Billetterie</option></select></label><label><span>Départ</span><select><option>Khemis Miliana</option></select></label><button className="search-btn" onClick={doSearch}><Search size={19}/> Rechercher</button></div></div>
  </section>
  <section className="section"><div className="container"><div className="section-top"><div><span className="kicker">DÉCOUVRIR</span><h2>Des voyages pensés pour vous.</h2></div><button className="text-link" onClick={()=>router.push('/destinations')}>Voir toutes les destinations <ArrowRight size={17}/></button></div><div className="destination-grid">{trips.slice(0,4).map(t=><TripCard key={t.id} t={t} favorites={favorites} toggleFavorite={toggleFavorite} compare={compare} toggleCompare={toggleCompare} router={router}/>)}</div></div></section>
  <section className="dark-section"><div className="container split"><div><span className="kicker light">UNE EXPÉRIENCE SIMPLE</span><h2>De la première idée<br/>au départ.</h2><p>Explorez, comparez et envoyez votre demande. L’équipe Primatours vous accompagne ensuite avec les informations disponibles.</p><button className="btn btn-white" onClick={()=>router.push('/demande')}>Préparer mon voyage <ArrowRight size={17}/></button></div><div className="steps">{[['01','DISCOVER','Explorez les destinations'],['02','SEARCH','Affinez votre recherche'],['03','REQUEST','Demandez un programme'],['04','CONTACT','Échangez avec l’agence']].map(s=><div className="step" key={s[0]}><b>{s[0]}</b><div><span>{s[1]}</span><strong>{s[2]}</strong></div></div>)}</div></div></section>
  <section className="section"><div className="container"><div className="section-top"><div><span className="kicker">SERVICES</span><h2>Tout au même endroit.</h2></div></div><div className="service-grid">{[['Omra','Accompagnement et programme sur demande','/omra',Globe2],['Billetterie','Une demande claire, traitée par l’agence','/billetterie',Plane],['Hôtels','Recherche et réservation sur demande','/hotels',Hotel]].map(([title,desc,href,Icon]:any)=><button className="service-card" key={href} onClick={()=>router.push(href)}><span className="icon-box"><Icon size={22}/></span><h3>{title}</h3><p>{desc}</p><ArrowRight/></button>)}</div></div></section>
  <section className="cta-band"><div className="container cta-inner"><div><span className="kicker light">KHÉMIS MILIANA</span><h2>Une question sur votre prochain voyage ?</h2><p>Parlez directement à Primatours.</p></div><div className="cta-buttons"><a className="btn btn-white" href={PHONE}><Phone size={18}/> 0672 78 37 89</a><a className="btn btn-orange" href={whatsapp('Bonjour Primatours Khemis Miliana, je souhaite préparer un voyage.')}>WhatsApp <MessageCircle size={18}/></a></div></div></section>
 </main>
}

function SearchBar({query,setQuery,doSearch}:{query:string,setQuery:(x:string)=>void,doSearch:()=>void}){return <div className="compact-search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&doSearch()} placeholder="Destination, ville ou type de voyage..."/><button onClick={doSearch}>Rechercher</button></div>}

function Listing({title,subtitle,query,setQuery,doSearch,favorites,toggleFavorite,compare,toggleCompare}:{title:string,subtitle:string,query:string,setQuery:(x:string)=>void,doSearch:()=>void,favorites:string[],toggleFavorite:(x:string)=>void,compare:string[],toggleCompare:(x:string)=>void}){const [type,setType]=useState('Tous');const [mobileFilters,setMobileFilters]=useState(false);const filtered=useMemo(()=>trips.filter(t=>type==='Tous'||t.type.includes(type)),[type]);return <main className="listing"><div className="container page-head"><span className="kicker">PRIMATOURS · KHÉMIS MILIANA</span><h1>{title}</h1><p>{subtitle}</p><SearchBar query={query} setQuery={setQuery} doSearch={doSearch}/></div><div className="container result-layout"><aside className={mobileFilters?'filters open':'filters'}><div className="filter-title"><b>Filtres</b><button onClick={()=>setMobileFilters(false)}><X size={18}/></button></div><label>Destination<input placeholder="Ex. Istanbul"/></label><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option>Tous</option><option>Voyage</option><option>Omra</option></select></label><label>Date<input type="date"/></label><label>Voyageurs<select><option>2 voyageurs</option><option>1 voyageur</option><option>3+ voyageurs</option></select></label><label>Budget<select><option>Tout budget</option><option>Sur demande</option></select></label><div className="filter-tags"><span>Famille</span><span>Plage</span><span>Culture</span><span>Luxe</span></div></aside><div className="results"><div className="results-bar"><b>{filtered.length} idées de voyage</b><div><button className="filter-mobile" onClick={()=>setMobileFilters(true)}><SlidersHorizontal size={17}/> Filtres</button><select><option>Pertinence</option><option>Prix croissant</option><option>Date</option></select></div></div><div className="results-grid">{filtered.map(t=><TripCard key={t.id} t={t} favorites={favorites} toggleFavorite={toggleFavorite} compare={compare} toggleCompare={toggleCompare} router={null}/>)}</div></div><div className="map-card"><div className="map-grid"/><div className="map-title"><MapPin size={18}/> Carte des destinations</div>{trips.slice(0,5).map((t,i)=><button key={t.id} className={`map-pin pin-${i+1}`} title={t.title}><MapPin size={20}/></button>)}<div className="map-note">OpenStreetMap · aperçu conceptuel</div></div></div>{compare.length>0&&<div className="compare-bar"><span><Scale size={18}/> {compare.length} voyage{compare.length>1?'s':''} sélectionné{compare.length>1?'s':''}</span><button onClick={()=>location.assign('/compare')}>Comparer</button></div>}</main>}

function TripCard({t,favorites,toggleFavorite,compare,toggleCompare,router}:{t:any,favorites:string[],toggleFavorite:(x:string)=>void,compare:string[],toggleCompare:(x:string)=>void,router:any}){return <article className="trip-card"><div className="card-image"><img src={t.image} alt={t.title}/><span className="pill">{t.type}</span><button className={favorites.includes(t.id)?'heart active':'heart'} onClick={()=>toggleFavorite(t.id)} aria-label="Ajouter aux favoris"><Heart size={18} fill={favorites.includes(t.id)?'currentColor':'none'}/></button></div><div className="card-body"><div className="muted"><MapPin size={14}/> {t.country}</div><h3>{t.title}</h3><p>{t.style}</p><div className="meta"><span><CalendarDays size={14}/> {t.duration}</span><span><Plane size={14}/> {t.departure}</span></div><div className="card-footer"><b>Prix sur demande</b><button onClick={()=>router?router.push(`/voyages/${t.id}`):location.assign(`/voyages/${t.id}`)}>Voir le voyage <ArrowRight size={15}/></button></div><div className="card-tools"><button onClick={()=>toggleCompare(t.id)} className={compare.includes(t.id)?'selected':''}><Scale size={15}/> {compare.includes(t.id)?'Ajouté':'Comparer'}</button><button onClick={()=>navigator.share?navigator.share({title:t.title,url:location.href}):navigator.clipboard.writeText(location.href)}><Share2 size={15}/> Partager</button></div></div></article>}

function Destination({slug,router}:{slug:string,router:any}){const t=trips.find(x=>x.id===slug)||trips[0];return <main><section className="detail-hero" style={{backgroundImage:`url(${t.image})`}}><div className="hero-overlay"/><div className="container detail-content"><span className="pill">{t.type}</span><h1>{t.title}</h1><p>{t.country} · {t.style}</p></div></section><section className="section"><div className="container detail-grid"><div><span className="kicker">PRIMATOURS</span><h2>Préparez votre voyage à {t.title}</h2><p className="lead">Une expérience construite selon vos dates, votre budget et vos besoins. Les programmes et disponibilités sont communiqués sur demande.</p><div className="info-row"><div><b>Destination</b><span>{t.country}</span></div><div><b>Durée</b><span>{t.duration}</span></div><div><b>Départ</b><span>{t.departure}</span></div></div><h3>Ce que vous pouvez demander</h3><ul className="checks"><li><Check/> Programme personnalisé</li><li><Check/> Informations sur les hôtels</li><li><Check/> Billetterie selon votre demande</li><li><Check/> Assistance par l’agence</li></ul></div><aside className="request-card"><span className="icon-box"><Sparkles/></span><h3>Intéressé par cette destination ?</h3><p>Envoyez votre demande et Primatours vous répondra avec les informations disponibles.</p><button className="btn btn-red" onClick={()=>router.push('/demande')}>Demander ce voyage <ArrowRight size={17}/></button><a href={whatsapp(`Bonjour Primatours, je suis intéressé par ${t.title}. Pouvez-vous m'envoyer les détails ?`)}>Contacter sur WhatsApp</a></aside></div></section></main>}

function ServicePage({kind,router}:{kind:'omra'|'ticket'|'hotel',router:any}){const data=kind==='omra'?{title:'Omra',desc:'Demandez le programme Omra adapté à votre projet.',icon:Globe2,fields:['Ville de départ','Période souhaitée','Nombre de voyageurs','Préférences / message']} : kind==='ticket'?{title:'Billetterie',desc:'Une demande de billet claire, sans inventaire fictif.',icon:Ticket,fields:['Départ','Destination','Date aller','Date retour','Voyageurs','Classe','Bagages','Nom','Téléphone','Email']} : {title:'Hôtels',desc:'Recherchez un hébergement selon vos dates et préférences.',icon:BedDouble,fields:['Destination','Check-in','Check-out','Adultes','Enfants','Chambres','Catégorie','Budget','Préférences']};return <main className="service-page"><section className="service-hero"><div className="container"><span className="icon-box big"><data.icon size={30}/></span><span className="kicker">SERVICE PRIMATOURS</span><h1>{data.title}</h1><p>{data.desc}</p></div></section><section className="section"><div className="container form-layout"><div><h2>{kind==='omra'?'Demander le programme Omra':kind==='ticket'?'Demander un billet':'Demander une réservation hôtel'}</h2><p className="lead">Les détails réels, prix et disponibilités sont confirmés par l’agence. Aucun inventaire fictif n’est affiché.</p><form className="form" onSubmit={e=>{e.preventDefault();router.push('/contact')}}><div className="form-grid">{data.fields.map(f=><label key={f}>{f}<input placeholder={f}/></label>)}</div><label>Message<textarea rows={5} placeholder="Précisez votre demande..."/></label><button className="btn btn-red btn-lg">Envoyer ma demande <ArrowRight size={17}/></button></form></div><aside className="side-note"><Check/><div><b>Simple et transparent</b><p>Vous envoyez une demande. L’agence confirme ensuite les informations disponibles.</p></div></aside></div></section></main>}

function RequestPage(){return <main className="request-page"><div className="container request-wrap"><div><span className="kicker">VOTRE PROJET</span><h1>Parlez-nous de votre voyage.</h1><p>Décrivez votre besoin. Nous vous recontactons avec les informations disponibles.</p><div className="request-points"><span><MessageCircle/> Réponse par téléphone ou WhatsApp</span><span><Check/> Pas de prix inventés</span><span><MapPin/> Khemis Miliana</span></div></div><form className="request-form" onSubmit={e=>{e.preventDefault();alert('Votre demande a été préparée. Contactez Primatours pour la suite.')}}><div className="form-grid"><label>Nom et prénom<input required/></label><label>Téléphone<input required/></label><label>Email<input type="email"/></label><label>Type de demande<select><option>Voyage</option><option>Omra</option><option>Billetterie</option><option>Hôtel</option></select></label><label>Destination<input placeholder="Ex. Istanbul"/></label><label>Date souhaitée<input type="date"/></label><label>Voyageurs<input type="number" min="1" defaultValue="2"/></label><label>Budget<input placeholder="Sur demande"/></label></div><label>Message<textarea rows={6} placeholder="Parlez-nous de votre projet..."/></label><button className="btn btn-red btn-lg">Envoyer la demande <ArrowRight size={18}/></button></form></div></main>}

function Branches({router}:{router:any}){const branches=[['Khemis Miliana','Rue Belsaadi Abdelkader','0672 78 37 89','0672 78 37 89'],['Dely Ibrahim','Bois des Cars II, lot A','0561 23 76 97',''],['Ferdjioua','Informations à confirmer','0668 67 33 54',''],['El Bordj','Informations à confirmer','0699 56 64 26','']];return <main className="section"><div className="container"><div className="page-head simple"><span className="kicker">RÉSEAU PRIMATOURS</span><h1>Nos agences</h1><p>Une architecture prête pour représenter le réseau Primatours. Les informations de chaque agence restent distinctes.</p></div><div className="branch-grid">{branches.map(b=><article className="branch-card" key={b[0]}><span className="icon-box"><MapPin/></span><h3>PRIMATOURS · {b[0]}</h3><p>{b[1]}</p><a href={`tel:${b[2].replaceAll(' ','')}`}><Phone size={16}/> {b[2]}</a>{b[3]&&<a href={whatsapp('Bonjour Primatours Khemis Miliana, je souhaite obtenir des informations.')}><MessageCircle size={16}/> WhatsApp</a>}<button onClick={()=>router.push('/contact')}>Voir les coordonnées <ArrowRight size={16}/></button></article>)}</div></div></main>}

function About({router}:{router:any}){return <main className="section"><div className="container about"><span className="kicker">À PROPOS</span><h1>Une nouvelle façon de découvrir Primatours.</h1><p className="lead">Ce site transforme la présence digitale de l’agence en une expérience de découverte et de demande, pensée pour les visiteurs qui arrivent depuis Google, Facebook, Instagram ou TikTok.</p><div className="about-grid"><div><h2>Une expérience orientée voyage</h2><p>Recherche, destinations, programmes, favoris, comparaison et contact sont réunis dans un parcours simple. Les informations non confirmées restent sur demande.</p></div><div><h2>Focus Khemis Miliana</h2><p>La branche de Khemis Miliana est au centre de l’expérience, avec ses coordonnées dédiées et des actions rapides Appeler, WhatsApp et Demander.</p></div></div><button className="btn btn-red" onClick={()=>router.push('/demande')}>Préparer mon voyage <ArrowRight/></button></div></main>}

function Contact(){return <main className="section"><div className="container contact-grid"><div><span className="kicker">CONTACT</span><h1>Parlons de votre prochain départ.</h1><p className="lead">PRIMATOURS · Khemis Miliana</p><div className="contact-list"><a href={PHONE}><Phone/><span><small>Téléphone</small>0672 78 37 89</span></a><a href="tel:+213795768866"><Phone/><span><small>Téléphone secondaire</small>0795 76 88 66</span></a><a href={whatsapp('Bonjour Primatours Khemis Miliana, je souhaite obtenir des informations.')}><MessageCircle/><span><small>WhatsApp</small>0672 78 37 89</span></a><a href="mailto:primatourskh@gmail.com"><span className="contact-symbol">@</span><span><small>Email</small>primatourskh@gmail.com</span></a><div className="address"><MapPin/><span><small>Adresse</small>شارع بلسعدي عبد القادر · خميس مليانة · 44225 · Algérie</span></div></div></div><div className="contact-map"><div className="map-grid"/><MapPin size={38}/><b>Khemis Miliana</b><span>Adresse fournie par l’agence</span><a className="btn btn-white" href="https://www.openstreetmap.org/search?query=Khemis%20Miliana%20Algeria" target="_blank">Itinéraire <ArrowRight size={17}/></a></div></div></main>}

function Favorites({favorites,toggleFavorite,router}:{favorites:string[],toggleFavorite:(x:string)=>void,router:any}){const items=trips.filter(t=>favorites.includes(t.id));return <main className="section"><div className="container page-head simple"><span className="kicker">VOTRE SÉLECTION</span><h1>Favoris</h1><p>Vos voyages enregistrés restent disponibles sur cet appareil.</p></div><div className="container results-grid">{items.length?items.map(t=><TripCard key={t.id} t={t} favorites={favorites} toggleFavorite={toggleFavorite} compare={[]} toggleCompare={()=>{}} router={router}/>):<div className="empty"><Heart/><h3>Aucun favori pour le moment.</h3><button className="btn btn-red" onClick={()=>router.push('/voyages')}>Explorer les voyages</button></div>}</div></main>}

function Compare({compare,toggleCompare,router}:{compare:string[],toggleCompare:(x:string)=>void,router:any}){const items=trips.filter(t=>compare.includes(t.id));return <main className="section"><div className="container page-head simple"><span className="kicker">COMPARAISON</span><h1>Comparer les voyages</h1><p>Comparez jusqu’à trois idées avant de faire votre demande.</p></div><div className="container compare-grid">{items.map(t=><article className="compare-card" key={t.id}><img src={t.image} alt=""/><button onClick={()=>toggleCompare(t.id)}><X/></button><h3>{t.title}</h3><p>{t.country}</p><dl><dt>Type</dt><dd>{t.type}</dd><dt>Durée</dt><dd>{t.duration}</dd><dt>Départ</dt><dd>{t.departure}</dd><dt>Prix</dt><dd>Sur demande</dd></dl><button className="btn btn-red" onClick={()=>router.push(`/voyages/${t.id}`)}>Voir le voyage</button></article>)}{!items.length&&<div className="empty"><Scale/><h3>Ajoutez des voyages à comparer.</h3><button className="btn btn-red" onClick={()=>router.push('/voyages')}>Explorer</button></div>}</div></main>}

function Footer({router}:{router:any}){return <footer><div className="container footer-grid"><div><button className="brand footer-brand" onClick={()=>router.push('/')}><span className="brand-orbit"><Globe2 size={24}/></span><span><b>PRIMA</b><strong>TOURS</strong><small>AGENCE DE VOYAGE</small></span></button><p>Votre voyage commence ici.</p></div><div><b>Découvrir</b><button onClick={()=>router.push('/voyages')}>Voyages</button><button onClick={()=>router.push('/destinations')}>Destinations</button><button onClick={()=>router.push('/offres')}>Offres</button></div><div><b>Services</b><button onClick={()=>router.push('/omra')}>Omra</button><button onClick={()=>router.push('/billetterie')}>Billetterie</button><button onClick={()=>router.push('/hotels')}>Hôtels</button></div><div><b>Contact</b><a href={PHONE}>0672 78 37 89</a><a href="mailto:primatourskh@gmail.com">primatourskh@gmail.com</a><span>Khemis Miliana, Algérie</span></div></div><div className="container footer-bottom"><span>© 2026 PRIMATOURS · Khemis Miliana</span><span>Informations et disponibilités sur demande.</span></div></footer>}
