'use client';
import { useParams, useRouter } from 'next/navigation';
import { ArrowRight, Check, MapPin, MessageCircle, Plane, Sparkles } from 'lucide-react';

const data: Record<string,{title:string;country:string;type:string;style:string;image:string}> = {
  istanbul:{title:'Istanbul',country:'Turquie',type:'Voyage international',style:'Culture · City break',image:'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1600&q=85'},
  dubai:{title:'Dubai',country:'Émirats arabes unis',type:'Voyage international',style:'Luxe · Shopping',image:'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1600&q=85'},
  tunis:{title:'Tunis',country:'Tunisie',type:'Voyage international',style:'Plage · Culture',image:'https://images.unsplash.com/photo-1530406831759-347e4f3e5e9f?auto=format&fit=crop&w=1600&q=85'},
  omra:{title:'Omra',country:'Arabie Saoudite',type:'Omra',style:'Religieux',image:'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&w=1600&q=85'},
  paris:{title:'Paris',country:'France',type:'Voyage international',style:'Culture · City break',image:'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=85'},
  algerie:{title:'Algérie',country:'Algérie',type:'Voyage local',style:'Aventure · Culture',image:'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1600&q=85'}
};
export default function TravelDetail(){const {slug}=useParams<{slug:string}>();const router=useRouter();const t=data[slug]||data.istanbul;const whatsapp=`https://wa.me/213672783789?text=${encodeURIComponent(`Bonjour Primatours, je suis intéressé par ${t.title}. Pouvez-vous m'envoyer les détails ?`)}`;return <main><section className="detail-hero" style={{backgroundImage:`url(${t.image})`}}><div className="hero-overlay"/><div className="container detail-content"><span className="pill">{t.type}</span><h1>{t.title}</h1><p>{t.country} · {t.style}</p></div></section><section className="section"><div className="container detail-grid"><div><span className="kicker">PRIMATOURS · KHÉMIS MILIANA</span><h2>Préparez votre voyage à {t.title}</h2><p className="lead">Les programmes, prix et disponibilités sont communiqués sur demande. Décrivez votre projet pour recevoir les informations disponibles auprès de l’agence.</p><div className="info-row"><div><b>Destination</b><span>{t.country}</span></div><div><b>Départ</b><span>Khemis Miliana</span></div><div><b>Tarif</b><span>Sur demande</span></div></div><h3>Votre demande peut inclure</h3><ul className="checks"><li><Check/> Programme personnalisé</li><li><Check/> Informations sur les hôtels</li><li><Check/> Billetterie selon la demande</li><li><Check/> Assistance de l’agence</li></ul></div><aside className="request-card"><span className="icon-box"><Sparkles/></span><h3>Cette destination vous intéresse ?</h3><p>Envoyez votre demande à Primatours Khemis Miliana.</p><button className="btn btn-red" onClick={()=>router.push('/demande')}>Demander ce voyage <ArrowRight size={16}/></button><a href={whatsapp}><MessageCircle size={16}/> Contacter sur WhatsApp</a></aside></div></section></main>}
